// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig, env } from "prisma/config";

// This file configures the Prisma CLI (migrate, studio, format, validate).
// It is NOT read by the running application — PrismaClient gets its
// connection string via the driver adapter in src/lib/db.ts instead.
// See docs/architecture.md for why Prisma 7 splits these two.
export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: env("DATABASE_URL"),
  },
});
